export const REQUEST_SNOOWRAP = 'REQUEST_SNOOWRAP';
export const RECEIVE_SNOOWRAP = 'RECEIVE_SNOOWRAP';
export const SNOOWRAP_ERROR = 'SNOOWRAP_ERROR';

export const REQUEST_POSTS = 'REQUEST_POSTS';
export const REQUEST_MORE_POSTS = 'REQUEST_MORE_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
